# Generated by Django 2.2.4 on 2019-08-29 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rgb', models.CharField(max_length=6)),
                ('transparent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('stud_count', models.PositiveIntegerField()),
                ('multi_height', models.BooleanField()),
                ('uneven_dimensions', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.PartCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UserPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Color')),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Part')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'part_id', 'color')},
            },
        ),
    ]
