# Generated by Django 2.2.4 on 2019-09-07 11:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_userpart_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpart',
            old_name='part_num',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='userpart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpart',
            unique_together={('user', 'part', 'color')},
        ),
    ]
