# Generated by Django 2.2.4 on 2019-09-09 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190907_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpart',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parts2', to='inventory.Color'),
        ),
        migrations.CreateModel(
            name='UserPartInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parts', to='inventory.Color')),
                ('userpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_list', to='inventory.UserPart')),
            ],
            options={
                'unique_together': {('userpart', 'color')},
            },
        ),
    ]
