# Generated by Django 2.2.4 on 2019-09-09 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_auto_20190909_1202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpart',
            unique_together={('user', 'part')},
        ),
        migrations.RemoveField(
            model_name='userpart',
            name='color',
        ),
        migrations.RemoveField(
            model_name='userpart',
            name='qty',
        ),
    ]
