# Generated by Django 2.2.5 on 2019-09-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_userpartinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='part_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
