# Generated by Django 2.2.5 on 2019-10-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190919_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='multi_height',
        ),
        migrations.RemoveField(
            model_name='part',
            name='stud_count',
        ),
        migrations.RemoveField(
            model_name='part',
            name='uneven_dimensions',
        ),
        migrations.CreateModel(
            name='ChildPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Alternate part', 'Part'), ('Different Mold', 'Mold'), ('Different Print', 'Print'), ('Different Pattern', 'Pattern')], max_length=32)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='child_relationship',
            field=models.ManyToManyField(through='inventory.ChildPart', to='inventory.Part'),
        ),
    ]
