# Generated by Django 2.2.5 on 2019-10-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20191017_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Alternate part', 'Part'), ('Different Mold', 'Mold'), ('Different Print', 'Print'), ('Different Pattern', 'Pattern')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='part',
            name='child_relationship',
            field=models.ManyToManyField(through='inventory.PartRelationship', to='inventory.Part'),
        ),
        migrations.DeleteModel(
            name='ChildPart',
        ),
        migrations.AddField(
            model_name='partrelationship',
            name='child_partt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='partrelationship',
            name='parent_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='inventory.Part'),
        ),
    ]
