# Generated by Django 2.2.5 on 2019-10-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20191017_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='child_relationship',
        ),
    ]
