# Generated by Django 2.2.5 on 2019-10-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20191019_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='category_id',
            new_name='category',
        ),
    ]
