# Generated by Django 2.2.5 on 2019-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20191020_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='bricklink_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='part',
            name='brickowl_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
