# Generated by Django 2.2.5 on 2019-10-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20191021_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='bricklink_id',
        ),
        migrations.RemoveField(
            model_name='part',
            name='brickowl_id',
        ),
        migrations.AlterUniqueTogether(
            name='partrelationship',
            unique_together={('child_part', 'parent_part')},
        ),
        migrations.CreateModel(
            name='PartExternalId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=32)),
                ('provider', models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickOwl', 'BrickOwl'), ('Brickset', 'Brickset'), ('Ldraw', 'Ldraw'), ('Lego', 'Lego')], max_length=32)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='inventory.Part')),
            ],
            options={
                'unique_together': {('part', 'provider', 'external_id')},
            },
        ),
    ]
