# Generated by Django 2.2.5 on 2019-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20191021_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partexternalid',
            name='provider',
            field=models.CharField(choices=[('BrickLink', 'BrickLink'), ('BrickOwl', 'BrickOwl'), ('Brickset', 'Brickset'), ('Ldraw', 'Ldraw'), ('Lego', 'Lego'), ('Peeron', 'Peeron')], max_length=32),
        ),
    ]
