# Generated by Django 2.2.6 on 2019-10-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20191022_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='rgb_complimentary',
            field=models.CharField(default=111, max_length=6),
            preserve_default=False,
        ),
    ]
