# Generated by Django 2.2.6 on 2019-10-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_color_rgb_complimentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='rgb_complimentary',
        ),
    ]
