# Generated by Django 2.2.6 on 2019-10-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_color_rgb_complimentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_step_hue',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='color_step_lumination',
            field=models.DecimalField(blank=True, decimal_places=20, editable=False, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='color_step_value',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
