# Generated by Django 2.2.6 on 2019-10-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20191027_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('transparent', 'color_step_hue', 'color_step_lumination', 'color_step_value')},
        ),
        migrations.CreateModel(
            name='SetPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_inventory', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('is_spare', models.BooleanField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_part_colors', to='inventory.Color')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_part_parts', to='inventory.Part')),
            ],
            options={
                'unique_together': {('set_inventory', 'part', 'color')},
            },
        ),
    ]
