# Generated by Django 2.2.6 on 2019-10-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20191027_1734'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setpart',
            unique_together={('set_inventory', 'part', 'color', 'is_spare')},
        ),
    ]
