# Generated by Django 2.2.6 on 2019-10-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20191029_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_step_hue',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_step_lumination',
            field=models.DecimalField(decimal_places=20, default=0, editable=False, max_digits=23),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_step_value',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
