# Generated by Django 2.2.6 on 2019-11-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20191029_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
