# Generated by Django 2.2.6 on 2019-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_part_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='stud_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
