# Generated by Django 2.2.6 on 2019-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_part_stud_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='underside_stud_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='underside_stud_ring_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
