# Generated by Django 2.2.6 on 2019-11-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20191129_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='underside_stud_count',
            new_name='bottom_studs',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='underside_stud_ring_count',
            new_name='stud_rings',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='stud_count',
            new_name='top_studs',
        ),
    ]
